package:
  name: dekupl-run
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

  host:
    - boost
    - cmake
    - zlib

  run:
    - pigz
    - jellyfish >2.2.0
    - snakemake-minimal
    - r-base
    - rpy2
    - r-rcolorbrewer
    - r-pheatmap
    - r-foreach
    - r-doparallel
    - bioconductor-deseq2 >=1.18.1

test:
  commands:
    - dekupl-run -v

about:
  home: https://github.com/Transipedia/dekupl-run
  license: MIT
  license_file: LICENSE
