variables:
  GIT_SUBMODULE_STRATEGY: recursive

# test:
#   image: registry.gitlab.com/siderax/dekupl-run:ci
#   stage: test
#   script:
#     - snakemake --configfile tests/config_transcript_to_gene_mapping.json
#     - snakemake --configfile tests/config_ttest.json
#     - snakemake --configfile tests/config_deseq2.json

delivery-conda:
  image: continuumio/miniconda3:4.5.11
  stage: test
  script:
    - conda info -a
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    - conda create -q -n build anaconda-client conda-build
    - conda activate build
    - conda build recipe
