sudo: required
dist: trusty
language: python
services:
  - docker
python: '3.6'
cache:
  directories:
    - /usr/local/lib/R/site-library
#r: release
#r: bioc-devel
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-math-dev
      - pigz
      - cmake
      #- r-base
      #- r-base-dev
before_install:
  # Install latest R version
  #- sudo add-apt-repository https://cloud.r-project.org/bin/linux/ubuntu trusty/
  - echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update
  - sudo apt-get -y install r-base r-base-dev
install:
  - pip install "snakemake<5.2.0"
  # Install all R packages
  - sudo Rscript install_r_packages.R
  # Install latest jellyfish version
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.9/jellyfish-2.2.9-linux-static
  - mv jellyfish-2.2.9-linux-static jellyfish
  - chmod +x jellyfish
  - export PATH=$PATH:$PWD
script:
  - snakemake --configfile tests/config_transcript_to_gene_mapping.json
  - snakemake --configfile tests/config_ttest.json
  - snakemake --configfile tests/config_deseq2.json
before_deploy:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh
  - bash Miniconda3-4.5.11-Linux-x86_64.sh -b -p $HOME/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n build python=$TRAVIS_PYTHON_VERSION anaconda-client
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda build recipe
deploy:
  # deploy docker
  - provider: script
    script: bash scripts/delivery-docker.sh
    on:
      tags: true
      branch: master
  # deploy conda
  - provider: script
    script: bash scripts/delivery-conda.sh
